// @ts-nocheck -- skip type checking
import * as docs_6 from "../content/docs/turbokit-vs-next-forge.mdx?collection=docs&hash=1770370636990"
import * as docs_5 from "../content/docs/layout-starters.mdx?collection=docs&hash=1770370636990"
import * as docs_4 from "../content/docs/index.mdx?collection=docs&hash=1770370636990"
import * as docs_3 from "../content/docs/getting-started.mdx?collection=docs&hash=1770370636990"
import * as docs_2 from "../content/docs/design-system.mdx?collection=docs&hash=1770370636990"
import * as docs_1 from "../content/docs/delivery-anti-drift.mdx?collection=docs&hash=1770370636990"
import * as docs_0 from "../content/docs/abbie-integration.mdx?collection=docs&hash=1770370636990"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"abbie-integration.mdx","absolutePath":"/Users/luke/Developer/apps/templates/turbokit/apps/docs/content/docs/abbie-integration.mdx"}, data: docs_0 }, { info: {"path":"delivery-anti-drift.mdx","absolutePath":"/Users/luke/Developer/apps/templates/turbokit/apps/docs/content/docs/delivery-anti-drift.mdx"}, data: docs_1 }, { info: {"path":"design-system.mdx","absolutePath":"/Users/luke/Developer/apps/templates/turbokit/apps/docs/content/docs/design-system.mdx"}, data: docs_2 }, { info: {"path":"getting-started.mdx","absolutePath":"/Users/luke/Developer/apps/templates/turbokit/apps/docs/content/docs/getting-started.mdx"}, data: docs_3 }, { info: {"path":"index.mdx","absolutePath":"/Users/luke/Developer/apps/templates/turbokit/apps/docs/content/docs/index.mdx"}, data: docs_4 }, { info: {"path":"layout-starters.mdx","absolutePath":"/Users/luke/Developer/apps/templates/turbokit/apps/docs/content/docs/layout-starters.mdx"}, data: docs_5 }, { info: {"path":"turbokit-vs-next-forge.mdx","absolutePath":"/Users/luke/Developer/apps/templates/turbokit/apps/docs/content/docs/turbokit-vs-next-forge.mdx"}, data: docs_6 }], [{"info":{"path":"meta.json","absolutePath":"/Users/luke/Developer/apps/templates/turbokit/apps/docs/content/docs/meta.json"},"data":{"title":"Documentation","pages":["index","getting-started","layout-starters","abbie-integration","design-system","delivery-anti-drift","turbokit-vs-next-forge"]}}])