export const IconNames = {
	X: "x",
	Check: "check",
	Circle: "circle",
	ChevronLeft: "chevron-left",
	ChevronRight: "chevron-right",
	ChevronDown: "chevron-down",
	ChevronUp: "chevron-up",
	PanelLeft: "panel-left",
	GripVertical: "grip-vertical",
	Search: "search",
	MoreHorizontal: "more-horizontal",
	Minus: "minus",
	ArrowLeft: "arrow-left",
	ArrowRight: "arrow-right",
	CaretRight: "caret-right",
	Bell: "bell",
	User: "user",
	Settings: "settings",
	FileText: "file-text",
	// Extended set for marketing/docs and utilities
	Github: "github",
	Twitter: "twitter",
	Sparkles: "sparkles",
	Zap: "zap",
	Code: "code",
	Users: "users",
	Globe: "globe",
	Database: "database",
	Workflow: "workflow",
	Bot: "bot",
	CheckCircle: "check-circle",
	Package: "package",
	Book: "book",
	Upload: "upload",
	Download: "download",
	Image: "image",
	File: "file",
	Trash: "trash",
	Eye: "eye",
	Palette: "palette",
	MagnifyingGlass: "magnifying-glass",
	// Admin/utility icons
	Plus: "plus",
	Star: "star",
	Lock: "lock",
	Pencil: "pencil",
	Copy: "copy",
	Sun: "sun",
	Moon: "moon",
} as const;

export type IconName = (typeof IconNames)[keyof typeof IconNames];
